// Generated by scripts/generate_model_contract.py. Do not edit manually.

export const CURRENT_MODEL_CONTRACT = {
  "schemaVersion": "current",
  "canonicalModel": "core8_independent_valuation",
  "scoringModelVersion": "core8_independent_valuation_current",
  "legacyScoringModelVersion": "v3_no_lookahead_replacement",
  "indicatorSet": "core8_bottom_independent_valuation_current",
  "displayIndicators": [
    "priceMa200w",
    "mvrvZscore",
    "nupl",
    "puell",
    "sthMvrv",
    "sthSopr",
    "lthMvrv",
    "lthSopr"
  ],
  "canonicalSignalKeys": [
    "priceMa200w",
    "mvrvZscore",
    "nupl",
    "puell",
    "sthMvrv",
    "sthSoprTrigger",
    "lthMvrv",
    "lthSopr"
  ],
  "compatibilityFields": [
    "priceRealized",
    "reserveRisk",
    "valuationBlendV6",
    "v2",
    "v4"
  ],
  "legacyCompatibility": [
    "v2",
    "v4"
  ],
  "latestCanonicalField": "canonical",
  "latestLegacyField": "legacy",
  "maxTotalScore": 14
} as const;

export const SCHEMA_VERSION = CURRENT_MODEL_CONTRACT.schemaVersion;
export const CANONICAL_MODEL = CURRENT_MODEL_CONTRACT.canonicalModel;
export const SCORING_MODEL_VERSION = CURRENT_MODEL_CONTRACT.scoringModelVersion;
export const LEGACY_SCORING_MODEL_VERSION = CURRENT_MODEL_CONTRACT.legacyScoringModelVersion;
export const CORE_INDICATOR_SET = CURRENT_MODEL_CONTRACT.indicatorSet;
export const DISPLAY_INDICATORS = CURRENT_MODEL_CONTRACT.displayIndicators;
export const CANONICAL_SIGNAL_KEYS = CURRENT_MODEL_CONTRACT.canonicalSignalKeys;
export const COMPATIBILITY_FIELDS = CURRENT_MODEL_CONTRACT.compatibilityFields;
export const LEGACY_COMPATIBILITY = CURRENT_MODEL_CONTRACT.legacyCompatibility;
export const LATEST_CANONICAL_FIELD = CURRENT_MODEL_CONTRACT.latestCanonicalField;
export const LATEST_LEGACY_FIELD = CURRENT_MODEL_CONTRACT.latestLegacyField;
export const MAX_TOTAL_SCORE = CURRENT_MODEL_CONTRACT.maxTotalScore;
