import type { IndicatorData } from '@/types';

export const CORE_HISTORY_FIELDS = [
  'unixTs',
  'btcPrice',
  'priceMa200wRatio',
  'priceRealizedRatio',
  'ma200w',
  'realizedPrice',
  'reserveRisk',
  'mvrvZscore',
  'nupl',
  'lthMvrv',
  'lthSopr',
  'lthSoprMa3',
  'sthSopr',
  'sthSoprMa3',
  'sthMvrv',
  'puellMultiple',
  'signalPriceMa200w',
  'signalPriceMa',
  'signalPriceRealized',
  'signalReserveRisk',
  'signalReserveRiskV4',
  'signalMvrvZscoreCore',
  'signalNupl',
  'signalNuplCore',
  'signalValuationBlendV6',
  'signalSthSopr',
  'signalSthMvrv',
  'signalSthGroup',
  'signalLthMvrv',
  'signalLthSopr',
  'signalSthSoprTrigger',
  'signalSthSoprAux',
  'signalPuell',
  'signalCount',
  'signalCountV4',
  'signalCountV6',
  'activeIndicatorCount',
  'activeIndicatorCountV4',
  'activeIndicatorCountV6',
  'maxSignalScoreV2',
  'scorePriceMa200w',
  'scorePriceRealized',
  'scoreReserveRisk',
  'scoreReserveRiskV4',
  'scoreMvrvZscore',
  'scoreMvrvZscoreCore',
  'scoreNupl',
  'scoreNuplCore',
  'valuationBlendScoreV6',
  'scoreLthMvrv',
  'scoreLthSopr',
  'scoreSthSopr',
  'scoreSthMvrv',
  'scoreSthGroup',
  'scorePuell',
  'signalScoreV2',
  'signalScoreV2Min3d',
  'signalConfirmed3d',
  'signalBandV2',
  'valuationScore',
  'maxValuationScore',
  'triggerScore',
  'maxTriggerScore',
  'confirmationScore',
  'maxConfirmationScore',
  'auxiliaryScore',
  'maxAuxiliaryScore',
  'totalScoreV4',
  'maxTotalScoreV4',
  'totalScoreV4Min3d',
  'signalConfirmed3dV4',
  'signalBandV4',
  'valuationScoreV6',
  'maxValuationScoreV6',
  'triggerScoreV6',
  'maxTriggerScoreV6',
  'confirmationScoreV6',
  'maxConfirmationScoreV6',
  'totalScoreV6',
  'maxTotalScoreV6',
  'totalScoreV6Min3d',
  'signalConfirmed3dV6',
  'signalBandV6',
  'signalConfidence',
  'signalConfidenceV6',
  'dataFreshnessScore',
  'dataFreshnessScoreV6',
  'fallbackMode',
  'fallbackModeV6',
  'staleIndicators',
  'indicatorSet',
  'coreIndicatorSet',
  'scoringModelVersion',
  'thresholds',
  'indicatorDates',
  'signalsV6',
] as const satisfies readonly (keyof IndicatorData)[];

export const CORE8_COVERAGE_FIELDS = [
  'priceMa200wRatio',
  'priceRealizedRatio',
  'mvrvZscore',
  'nupl',
  'lthMvrv',
  'lthSopr',
  'sthSopr',
  'sthMvrv',
  'puellMultiple',
] as const satisfies readonly (keyof IndicatorData)[];

export function missingCoreHistoryFields(fields: readonly string[] | undefined): string[] {
  if (!fields) {
    return [];
  }

  const available = new Set(fields);
  return CORE8_COVERAGE_FIELDS.filter((field) => !available.has(field));
}
