#!/usr/bin/env python3
"""Generate frontend and Edge runtime model-contract modules."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
CONTRACT_PATH = ROOT / "contracts" / "current_model.json"
FRONTEND_OUTPUT = ROOT / "app" / "src" / "services" / "generatedModelContract.ts"
EDGE_OUTPUT = ROOT / "app" / "api" / "generated-model-contract.js"


def _load_contract(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        payload = json.load(f)
    if not isinstance(payload, dict):
        raise ValueError(f"Model contract must be a JSON object: {path}")
    return payload


def _json_literal(payload: dict[str, Any]) -> str:
    return json.dumps(payload, ensure_ascii=False, indent=2)


def _build_frontend_module(contract: dict[str, Any]) -> str:
    contract_json = _json_literal(contract)
    return f"""// Generated by scripts/generate_model_contract.py. Do not edit manually.

export const CURRENT_MODEL_CONTRACT = {contract_json} as const;

export const SCHEMA_VERSION = CURRENT_MODEL_CONTRACT.schemaVersion;
export const CANONICAL_MODEL = CURRENT_MODEL_CONTRACT.canonicalModel;
export const SCORING_MODEL_VERSION = CURRENT_MODEL_CONTRACT.scoringModelVersion;
export const LEGACY_SCORING_MODEL_VERSION = CURRENT_MODEL_CONTRACT.legacyScoringModelVersion;
export const CORE_INDICATOR_SET = CURRENT_MODEL_CONTRACT.indicatorSet;
export const DISPLAY_INDICATORS = CURRENT_MODEL_CONTRACT.displayIndicators;
export const CANONICAL_SIGNAL_KEYS = CURRENT_MODEL_CONTRACT.canonicalSignalKeys;
export const COMPATIBILITY_FIELDS = CURRENT_MODEL_CONTRACT.compatibilityFields;
export const LEGACY_COMPATIBILITY = CURRENT_MODEL_CONTRACT.legacyCompatibility;
export const LATEST_CANONICAL_FIELD = CURRENT_MODEL_CONTRACT.latestCanonicalField;
export const LATEST_LEGACY_FIELD = CURRENT_MODEL_CONTRACT.latestLegacyField;
export const MAX_TOTAL_SCORE = CURRENT_MODEL_CONTRACT.maxTotalScore;
"""


def _build_edge_module(contract: dict[str, Any]) -> str:
    contract_json = _json_literal(contract)
    return f"""// Generated by scripts/generate_model_contract.py. Do not edit manually.

export const CURRENT_MODEL_CONTRACT = Object.freeze({contract_json});

export const SCHEMA_VERSION = CURRENT_MODEL_CONTRACT.schemaVersion;
export const CANONICAL_MODEL = CURRENT_MODEL_CONTRACT.canonicalModel;
export const SCORING_MODEL_VERSION = CURRENT_MODEL_CONTRACT.scoringModelVersion;
export const LEGACY_SCORING_MODEL_VERSION = CURRENT_MODEL_CONTRACT.legacyScoringModelVersion;
export const CORE_INDICATOR_SET = CURRENT_MODEL_CONTRACT.indicatorSet;
export const DISPLAY_INDICATORS = CURRENT_MODEL_CONTRACT.displayIndicators;
export const CANONICAL_SIGNAL_KEYS = CURRENT_MODEL_CONTRACT.canonicalSignalKeys;
export const COMPATIBILITY_FIELDS = CURRENT_MODEL_CONTRACT.compatibilityFields;
export const LEGACY_COMPATIBILITY = CURRENT_MODEL_CONTRACT.legacyCompatibility;
export const LATEST_CANONICAL_FIELD = CURRENT_MODEL_CONTRACT.latestCanonicalField;
export const LATEST_LEGACY_FIELD = CURRENT_MODEL_CONTRACT.latestLegacyField;
export const MAX_TOTAL_SCORE = CURRENT_MODEL_CONTRACT.maxTotalScore;
"""


def _write_if_changed(path: Path, text: str) -> bool:
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == text:
        return False

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate model-contract modules.")
    parser.add_argument("--check", action="store_true", help="Fail if generated files are stale.")
    args = parser.parse_args()

    contract = _load_contract(CONTRACT_PATH)
    outputs = {
        FRONTEND_OUTPUT: _build_frontend_module(contract),
        EDGE_OUTPUT: _build_edge_module(contract),
    }

    stale_paths: list[Path] = []
    for path, text in outputs.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale_paths.append(path)
            continue
        _write_if_changed(path, text)

    if stale_paths:
        print("Generated model-contract files are stale:")
        for path in stale_paths:
            print(f"- {path.relative_to(ROOT)}")
        print("Run: python scripts/generate_model_contract.py")
        return 1

    if not args.check:
        print("Model-contract modules generated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
